"""Build the Assignment 3 PDF from the submitted source and browser evidence.

Run from any directory: python assignment3/scripts/build_report.py
Dependencies: pip install -r assignment3/scripts/requirements-report.txt
Screenshots and verification results are generated by scripts/verify.py.
The complete report uses actual browser captures, never reconstructed mockups.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from xml.sax.saxutils import escape

from PIL import Image
from fontTools.ttLib import TTFont as FontToolsFont
from fontTools.varLib.instancer import instantiateVariableFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, Table, TableStyle

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Assignment3_Alimzhan_Almukhambetov.pdf"
SHOTS = ROOT / "evidence" / "screenshots"
TMP = ROOT / "tmp" / "report-qa"
PAPER = colors.HexColor("#f5f2e9")
INK = colors.HexColor("#24251f")
ORANGE = colors.HexColor("#f45d32")
MUTED = colors.HexColor("#64665b")
LINE = colors.HexColor("#d4d4c9")
REPO = "https://github.com/xnionn/WEB-midterm"
SOURCE = REPO + "/tree/main/assignment3"
SITE = "https://xnionn.github.io/WEB-midterm/assignment3/"
STYLES: dict[str, ParagraphStyle] = {}


def fonts() -> None:
    """Convert licensed local WOFF2 fonts to embedded static PDF fonts."""
    cache = ROOT / "tmp" / "report-fonts"
    cache.mkdir(parents=True, exist_ok=True)
    for name, filename, weight in (
        ("Space", "space-grotesk-latin-variable.woff2", 600),
        ("DM", "dm-sans-latin-variable.woff2", 400),
        ("DM-Bold", "dm-sans-latin-variable.woff2", 700),
    ):
        dest = cache / (name + ".ttf")
        if not dest.exists():
            src = ROOT / "assets" / "fonts" / filename
            if not src.exists():
                raise FileNotFoundError(f"Missing local font: {src}")
            font = FontToolsFont(src)
            axes = {axis.axisTag: axis.defaultValue for axis in font["fvar"].axes}
            axes["wght"] = weight
            font = instantiateVariableFont(font, axes, inplace=True)
            font.flavor = None
            for record in font["name"].names:
                if record.nameID in (1, 4, 6):
                    record.string = ("Assignment3Report" + name).encode(record.getEncoding())
            font.save(dest)
        pdfmetrics.registerFont(TTFont(name, str(dest)))
    pdfmetrics.registerFontFamily("DM", normal="DM", bold="DM-Bold", italic="DM", boldItalic="DM-Bold")
    for name, font, size, leading, color in (
        ("body", "DM", 11, 16, INK),
        ("small", "DM", 9.4, 13.3, MUTED),
        ("table", "DM", 9.5, 13.2, INK),
        ("table-head", "DM-Bold", 9.5, 13.2, colors.white),
    ):
        STYLES[name] = ParagraphStyle(name, fontName=font, fontSize=size, leading=leading, textColor=color)


class Report:
    def __init__(self) -> None:
        self.c = canvas.Canvas(str(OUT), pagesize=A4, pageCompression=1)
        self.c.setTitle("Assignment 3 - Responsive Web Design - Alimzhan Almukhambetov")
        self.c.setAuthor("Alimzhan Almukhambetov")
        self.c.setSubject("WEB Technologies 1; IT-2510; mobile-first CSS and Bootstrap 5.3")
        self.page_number = 0
        self.width, self.height = A4

    def new(self, label: str, title: str, *, wide: bool = False) -> float:
        if self.page_number:
            self.c.showPage()
        self.page_number += 1
        self.width, self.height = landscape(A4) if wide else A4
        c = self.c
        c.setPageSize((self.width, self.height))
        c.setFillColor(PAPER)
        c.rect(0, 0, self.width, self.height, fill=1, stroke=0)
        c.setFillColor(ORANGE)
        c.setFont("DM-Bold", 9)
        c.drawString(42, self.height - 42, label.upper())
        c.setFillColor(INK)
        c.setFont("Space", 25)
        c.drawString(42, self.height - 77, title)
        c.setStrokeColor(LINE)
        c.line(42, 41, self.width - 42, 41)
        c.setFillColor(MUTED)
        c.setFont("DM", 8)
        c.drawString(42, 25, "OFFLINE / Assignment 3 / Alimzhan Almukhambetov / IT-2510")
        c.drawRightString(self.width - 42, 25, f"{self.page_number:02}")
        return self.height - 100

    def para(self, text: str, y: float, *, x: float = 42, width: float | None = None, style: str = "body") -> float:
        p = Paragraph(text, STYLES[style])
        _, height = p.wrap(width or self.width - x - 42, 1200)
        if y - height < 55:
            raise ValueError(f"Text overflow on page {self.page_number}: {text[:65]}")
        p.drawOn(self.c, x, y - height)
        return y - height - 11

    def heading(self, title: str, y: float, *, x: float = 42, size: float = 16) -> float:
        self.c.setFont("Space", size)
        self.c.setFillColor(INK)
        self.c.drawString(x, y - size, title)
        return y - size - 12

    def table(self, rows: list[list[str]], y: float, widths: list[float]) -> float:
        cells = [[Paragraph(escape(cell), STYLES["table-head" if i == 0 else "table"])
                  for cell in row] for i, row in enumerate(rows)]
        t = Table(cells, colWidths=widths)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eeeee6")]),
            ("LINEBELOW", (0, 0), (-1, -1), .5, LINE),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        _, height = t.wrap(sum(widths), 1400)
        if y - height < 55:
            raise ValueError(f"Table overflow on page {self.page_number}")
        t.drawOn(self.c, 42, y - height)
        return y - height - 18

    def code(self, lines: str, y: float, *, width: float | None = None, size: float = 8.5) -> float:
        content = lines.strip("\n").splitlines()
        leading = size * 1.52
        h = 24 + leading * len(content)
        if y - h < 55:
            raise ValueError(f"Code overflow on page {self.page_number}")
        self.c.setFillColor(INK)
        self.c.roundRect(42, y - h, width or self.width - 84, h, 4, stroke=0, fill=1)
        self.c.setFillColor(colors.HexColor("#fffdf5"))
        self.c.setFont("Courier", size)
        for i, line in enumerate(content):
            self.c.drawString(54, y - 17 - i * leading, line)
        return y - h - 18

    def picture(self, name: str, x: float, y: float, w: float, h: float, *, crop: tuple[int, int, int, int] | None = None) -> tuple[float, float]:
        path = SHOTS / name
        im = Image.open(path)
        if crop:
            im = im.crop(crop)
        scale = min(w / im.width, h / im.height)
        dw, dh = im.width * scale, im.height * scale
        self.c.setFillColor(colors.white)
        self.c.setStrokeColor(LINE)
        self.c.rect(x + (w - dw) / 2, y + h - dh, dw, dh, fill=1, stroke=1)
        self.c.drawImage(ImageReader(im), x + (w - dw) / 2, y + h - dh, dw, dh, mask="auto")
        return dw, dh

    def save(self) -> None:
        self.c.save()


def cover(r: Report) -> None:
    y = r.new("Astana IT University / WEB Technologies 1", "Responsive Web Design")
    y = r.para("<b>Assignment 3</b><br/>Media Queries + Bootstrap Grid", y - 3)
    r.c.setFillColor(ORANGE)
    r.c.setFont("Space", 60)
    r.c.drawString(42, y - 78, "OFFLINE")
    y -= 113
    y = r.para("One page for a fictional campus club where students make things together and take a break from screens.", y)
    y = r.table([
        ["Student", "Group"],
        ["Alimzhan Almukhambetov", "IT-2510"],
    ], y - 8, [352, 159.3])
    y = r.para("<b>Report date:</b> 3 October 2026<br/><b>Format:</b> individual assignment; one responsive page", y)
    y = r.heading("Source and published page", y - 7)
    for label, url in (("GitHub repository", REPO), ("Assignment source folder", SOURCE), ("Published website", SITE)):
        y = r.para(f'<b>{label}</b><br/><link href="{url}" color="#24251f">{url}</link>', y, style="small")
    r.para("The assignment is stored separately in <b>assignment3/</b>. The OFFLINE concept, local fonts and visual language are adapted from the existing midterm project; this page has its own markup, stylesheet and responsive implementation.", y - 11, style="small")


def task_one(r: Report) -> None:
    y = r.new("Task 1 / Media queries by hand", "One grid, three arrangements")
    y = r.para("The repeated ritual cards use native CSS Grid. The section contains only project-specific classes: there are no Bootstrap grid or utility classes inside it. Its fluid container grows with available space and the cards use fractional tracks instead of fixed pixel widths.", y)
    y = r.table([
        ["Viewport", "Custom rule", "Result"],
        ["375 px", "Base CSS", "One card per row"],
        ["768 px", "@media (min-width: 48rem)", "Two cards per row"],
        ["1280 px", "@media (min-width: 64rem)", "Three cards per row"],
    ], y, [86, 239, 186.3])
    y = r.heading("How mobile-first works", y)
    y = r.para("The base rule is the phone layout. A min-width query adds an override once the viewport is wide enough. At 48rem, the heading grows from 2rem to 2.5rem, section padding from 2.75rem to 3.5rem, and grid gap from 1.5rem to 2rem. The query changes both the layout and its spacing.", y)
    y = r.code(""".ritual-grid {
  display: grid;
  grid-template-columns: 1fr;
}
@media (min-width: 48rem) {
  .ritual-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (min-width: 64rem) {
  .ritual-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
}""", y)
    r.para("The excerpt isolates the layout rules; style.css also contains the section spacing, typography, colors and interactive states. There are no floats or absolutely positioned layout elements in the section.", y, style="small")


def task_one_screens(r: Report) -> None:
    y = r.new("Task 1 / Responsive evidence", "Phone and tablet", wide=True)
    r.para("Left: 375 px, cropped to the three stacked items. Right: 768 px, the full section with two columns. The same cards stay in document order.", y, style="small")
    r.picture("task1-rituals-375.png", 42, 64, 245, 402, crop=(0, 277, 375, 892))
    r.picture("task1-rituals-768.png", 307, 64, 492, 402)
    y = r.new("Task 1 / Responsive evidence", "Laptop: the three-column grid", wide=True)
    r.para("1280 px. The custom 64rem query creates three tracks, preserving the section's own typography and spacing.", y, style="small")
    r.picture("task1-rituals-1280.png", 42, 60, r.width - 84, 405)


def task_two(r: Report) -> None:
    y = r.new("Task 2 / Bootstrap grid and components", "A shared grid for the rest")
    y = r.para("The other page sections use Bootstrap 5.3.8 from the official CDN: a container limits the line length, a row groups columns, and responsive col-* classes control their widths. The local stylesheet is linked after Bootstrap so the club's colors, buttons and card details can override the defaults.", y)
    y = r.table([
        ["Requirement", "Implementation on this page"],
        ["Responsive cards", "col-12 col-md-6 col-lg-4: one card below 768 px, two from 768 px, three from 992 px."],
        ["Stacked columns", "The hero uses responsive columns and order-* classes. Essential introduction text comes before the illustration on a phone."],
        ["Visibility", "The hero note uses d-none d-md-block, hiding it below 768 px. The navbar location uses d-none d-lg-block."],
        ["Spacing and alignment", "Bootstrap p-*, m-*, d-flex and text-* utilities combine with project-specific CSS."],
        ["Components", "A collapsing navbar and an accordion provide navigation and answers. The bundle supplies their behavior."],
    ], y, [123, 388.3])
    y = r.heading("Grid classes and breakpoints", y)
    y = r.code("""<div class="container">
  <div class="row g-4">
    <div class="col-12 col-md-6 col-lg-4">
      <article class="card">...</article>
    </div>
  </div>
</div>""", y)
    r.para("Bootstrap lg starts at 992 px; the manual section changes to three columns at 64rem (1024 px with the default font size). The two thresholds are intentionally distinct. At the three required test widths, both card sections produce the required 1 / 2 / 3 arrangements.", y, style="small")


def task_two_screens(r: Report) -> None:
    y = r.new("Task 2 / Responsive cards", "Stacked cards become columns", wide=True)
    r.para("Left: 375 px, a detail of the first two stacked cards. Right: 768 px, the first row of two cards. Crops retain the original proportions and arrangement.", y, style="small")
    r.picture("task2-cards-375.png", 42, 63, 245, 400, crop=(0, 188, 375, 797))
    r.picture("task2-cards-768.png", 307, 139, 492, 324, crop=(0, 120, 768, 626))
    r.para("The third card follows in the next row at 768 px. Full-resolution screenshots and the complete mobile sequence later in this report preserve all card content.", 118, x=307, width=492, style="small")
    y = r.new("Task 2 / Responsive cards", "Three cards across at 1280 px", wide=True)
    r.para("col-lg-4 gives each column four of Bootstrap's twelve grid units. The cards keep the same semantic article content.", y, style="small")
    r.picture("task2-cards-1280.png", 42, 61, r.width - 84, 401)
    y = r.new("Task 2 / Components and ordering", "Small-screen interactions", wide=True)
    r.para("The navbar button opens the section links. The accordion expands answers. The hero keeps its important copy first when the columns stack.", y, style="small")
    r.picture("navbar-375-open.png", 42, 225, 245, 233)
    r.para("Hero source order:<br/><b>1.</b> Introduction and actions<br/><b>2.</b> Poster illustration<br/><br/>At lg, order-lg-2 moves the copy to the right and order-lg-1 moves the poster left. On phones, the useful introduction stays first.", 218, x=42, width=245, style="small")
    r.picture("task2-faq-768.png", 307, 130, 492, 328)
    r.para("Bootstrap's bundle controls collapse state and aria-expanded. Native links navigate to section IDs. Custom CSS supplies the paper color, ink borders and visible keyboard focus.", 117, x=307, width=492, style="small")


def comparison(r: Report) -> None:
    y = r.new("Task 3 / Comparison", "Two ways to solve the same grid")
    y = r.para("Both sections place repeated cards in 1, 2 and 3 columns. The difference is where the responsive decisions live: the manual section states them in CSS, while the Bootstrap section selects an existing system through HTML classes.", y)
    y = r.table([
        ["Aspect", "Task 1: custom CSS", "Task 2: Bootstrap"],
        ["Layout code", "The ritual grid defines display: grid, its base track and two min-width overrides.", "The gathering columns use col-12 col-md-6 col-lg-4 inside row and container."],
        ["Design control", "48rem and 64rem are chosen for the ritual cards; spacing and heading changes share a query.", "md and lg use Bootstrap's existing 768 px and 992 px thresholds; own CSS adds the visual style."],
        ["Change process", "Changing the desktop track count means editing one grid-template-columns declaration.", "Changing col-lg-4 to col-lg-6 gives two equal columns at lg; the class must change on each column."],
        ["Reuse and behavior", "The grid needs no layout library. Any interactive behavior is a separate responsibility.", "The same framework also supplies the navbar and accordion, with its JavaScript bundle."],
    ], y, [80, 216, 215.3])
    y = r.heading("When to choose each approach", y)
    y = r.para("Custom CSS fits a section that needs its own proportions, spacing changes or content-specific breakpoints, like the ritual grid. Bootstrap fits a page with repeated conventional columns and standard interactions, like the gathering cards, navigation and FAQ. Combining them works well here because the custom section has a clear boundary and the rest shares one responsive system.", y)
    r.para("The comparison refers to this submitted page. Neither approach automatically supplies the site's visual identity; the palette, typography, hierarchy and content still need design decisions.", y, style="small")


def overviews(r: Report) -> None:
    y = r.new("Whole-page screenshots / browser evidence", "The complete page at three widths", wide=True)
    r.para("375 px / 768 px / 1280 px. These full-page overviews show the entire document; the following spread makes the mobile page readable from top to bottom.", y, style="small")
    for i, viewport in enumerate((375, 768, 1280)):
        full = Image.open(SHOTS / f"page-{viewport}.png")
        x = 42 + i * 256
        r.para(f"<b>{viewport} px</b><br/>{full.width} x {full.height} px capture", 465, x=x, width=238, style="small")
        r.picture(f"page-{viewport}.png", x, 62, 238, 364)
    full = Image.open(SHOTS / "page-375.png")
    # Six consecutive strips show every pixel at a readable scale. The
    # untouched full screenshot above establishes their document context.
    boundaries = [0, 665, 1340, 1938, 2565, 3210, full.height]
    for spread in range(2):
        y = r.new("Whole mobile page / readable continuation", f"375 px: reading sequence {spread + 1} of 2", wide=True)
        instruction = "Read left to right, then continue on the next page." if spread == 0 else "Read left to right to reach the footer."
        r.para(instruction + " These are consecutive, non-overlapping crops of the same full-page screenshot; no content is rearranged or omitted.", y, style="small")
        for col in range(3):
            idx = spread * 3 + col
            x = 42 + col * 256
            r.para(f"<b>Part {idx + 1} of 6</b> / y {boundaries[idx]}-{boundaries[idx + 1]} px", 455, x=x, width=238, style="small")
            r.picture("page-375.png", x, 59, 238, 377, crop=(0, boundaries[idx], 375, boundaries[idx + 1]))


def conclusion(r: Report, evidence: dict) -> None:
    y = r.new("Verification / conclusion / sources", "What the implementation demonstrates")
    y = r.para("The page combines a handmade CSS grid with Bootstrap's grid and components while keeping one visual style. The main takeaway is that responsive design changes the arrangement and priority of content, not only its size: columns stack, the hero preserves reading order, and secondary content can disappear on small screens.", y)
    y = r.para("Another takeaway is the importance of the cascade. Bootstrap is loaded first, the project stylesheet follows it, and a mobile-first query adds changes as the viewport grows. Testing the actual page at 375, 768 and 1280 px makes these decisions visible and helps catch horizontal overflow or an inaccessible menu.", y)
    y = r.heading("Verification", y)
    y = r.table([
        ["Check", "Observed result: passed"],
        ["375 / 768 / 1280 px", "Manual and Bootstrap card grids show 1 / 2 / 3 columns; no horizontal page scroll."],
        ["Navbar and accordion", "Menu toggles on a phone; navigation targets exist; answers expand and collapse."],
        ["Source and dependencies", "Viewport meta tag, official Bootstrap CDN links, local CSS after Bootstrap, bundle before </body>."],
    ], y, [148, 363.3])
    y = r.para(f"The hosted page passed all {len(evidence['checks'])} recorded checks at {len(evidence['widths'])} viewport widths, including the required sizes and breakpoint boundaries. The browser evidence was captured on 3 October 2026; full results are in evidence/deployed/verification.json.", y, style="small")
    y = r.heading("Credits and references", y)
    y = r.para("The topic and visual language reuse the existing OFFLINE midterm project with permission. Space Grotesk and DM Sans are stored locally under their included SIL Open Font License files. Bootstrap is used under its MIT license. AI tools assisted with implementation, report drafting and verification.", y, style="small")
    for title, url in (
        ("Bootstrap 5.3: introduction and CDN setup", "https://getbootstrap.com/docs/5.3/getting-started/introduction/"),
        ("Bootstrap 5.3: grid system", "https://getbootstrap.com/docs/5.3/layout/grid/"),
        ("Bootstrap 5.3: navbar", "https://getbootstrap.com/docs/5.3/components/navbar/"),
        ("Bootstrap 5.3: accordion", "https://getbootstrap.com/docs/5.3/components/accordion/"),
        ("W3Schools: CSS media queries", "https://www.w3schools.com/css/css3_mediaqueries.asp"),
    ):
        y = r.para(f'<link href="{url}" color="#24251f">{title}</link>', y, style="small")
    r.para("Course material: G. A. Abitova, Web Technologies Front-End Development, Part 2 (2022); Assignment 3 brief supplied for WEB Technologies 1.", y, style="small")


def render_and_check() -> dict:
    import pymupdf
    from pypdf import PdfReader
    TMP.mkdir(parents=True, exist_ok=True)
    doc = pymupdf.open(OUT)
    thumbs = []
    for i, page in enumerate(doc):
        pix = page.get_pixmap(matrix=pymupdf.Matrix(1.45, 1.45), alpha=False)
        path = TMP / f"page-{i + 1:02}.png"
        pix.save(path)
        im = Image.open(path).convert("RGB")
        im.thumbnail((340, 460))
        tile = Image.new("RGB", (370, 490), "#deded8")
        tile.paste(im, ((370 - im.width) // 2, 10))
        thumbs.append(tile)
    cols = 3
    sheet = Image.new("RGB", (cols * 370, ((len(thumbs) + cols - 1) // cols) * 490), "white")
    for i, tile in enumerate(thumbs):
        sheet.paste(tile, ((i % cols) * 370, (i // cols) * 490))
    sheet.save(TMP / "contact-sheet.png")
    reader = PdfReader(OUT)
    text = "\n".join(page.extract_text() or "" for page in reader.pages)
    for expected in ("Alimzhan Almukhambetov", "IT-2510", "Task 1", "Task 2", "Task 3", REPO, SOURCE, SITE):
        assert expected.lower() in text.lower(), expected
    links = [str(annotation.get_object().get("/A", {}).get("/URI", ""))
             for page in reader.pages for annotation in page.get("/Annots", [])]
    for url in (REPO, SOURCE, SITE):
        assert url in links, url
    report = {"pages": len(reader.pages), "bytes": OUT.stat().st_size, "required_text_and_links": "passed", "rendered_pages": len(doc), "visual_review": "required"}
    (TMP / "report-qa.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    return report


def main() -> None:
    global SHOTS
    parser = argparse.ArgumentParser()
    parser.add_argument("--screenshots", type=Path, default=SHOTS)
    args = parser.parse_args()
    SHOTS = args.screenshots.resolve()
    fonts()
    evidence_path = ROOT / "evidence" / "deployed" / "verification.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    if evidence.get("passed") is not True or any(not check.get("passed") for check in evidence["checks"]):
        raise ValueError("The report requires successful hosted verification evidence.")
    r = Report()
    cover(r)
    task_one(r)
    task_one_screens(r)
    task_two(r)
    task_two_screens(r)
    comparison(r)
    overviews(r)
    conclusion(r, evidence)
    r.save()
    print(json.dumps(render_and_check(), indent=2))


if __name__ == "__main__":
    main()
